package ProtocolSocket;

public enum ProtocolID {
	CLIENT_NICKNAME,
	CLIENT_JOINED,
	CLIENT_LEFT,
	CHANNEL_BROADCAST,
	PRIVATE_MESSAGE,
	CONNECTION_CLOSED,
	NICKNAME_NOT_VALID,
	LIST_CHANNELS,
	LIST_USERS,
	JOIN_CHANNEL,
	LEAVE_CHANNEL,

}
